@startuml class_pymatmc2.MultiCell
class pymatmc2.MultiCell{
    --properties--
    +n_atoms: int
    +cells: Dict[str, SimulationCell]
    --methods--
    + get_n_atoms(symbol): int
}

class mexm.io.vasp.Poscar
class mexm.SimulationCell

mexm.io.vasp.Poscar -> mexm.SimulationCell: extends >
mexm.io.vasp.Poscar *-- mexm.simulation.VaspSimulation
mexm.SimulationCell *-- mexm.Lattice
mexm.SimulationCell *-- mexm.AtomicBasis
mexm.AtomicBasis "1..N" *-- mexm.Atoms

mexm.simulation.Simulation *-- pymatmc2.MultiCell
mexm.SimulationCell *-- mexm.simulation.Simulation
mexm.simulation.VaspSimulation -> mexm.simulation.Simulation: extends >
@enduml

@startuml activity_pymatmc2.MultiCell.configure
start

:add cells;
:add total_molar_fraction;
end
@enduml